/**
* NOTE: This class is auto generated by the swagger code generator program (2.4.10).
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/
package br.com.rfernandon.demoswaggercodegen.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.service.ApiKey;
import springfox.documentation.service.Contact;
import springfox.documentation.service.BasicAuth;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;

import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-03-03T23:00:40.543-03:00")

@Configuration
public class SwaggerDocumentationConfig {

ApiInfo apiInfo() {
return new ApiInfoBuilder()
.title("Sample API")
.description("API description in Markdown")
.license("")
.licenseUrl("http://unlicense.org")
.termsOfServiceUrl("http://www.minha.api.com.br/service")
.version("1.0.0")
.contact(new Contact("Neves, Ricardo","http://www.minha.api.com.br/", "r.fernandon@gmail.com"))
.build();
}

@Bean
public Docket customImplementation(){
return new Docket(DocumentationType.SWAGGER_2)
.select()
.apis(RequestHandlerSelectors.basePackage("br.com.rfernandon.demoswaggercodegen.api"))
.build()
    .directModelSubstitute(java.time.LocalDate.class, java.sql.Date.class)
    .directModelSubstitute(java.time.OffsetDateTime.class, java.util.Date.class)
    .useDefaultResponseMessages(false)
            .securitySchemes(List.of(new BasicAuth("api_basic_auth")))
.apiInfo(apiInfo());
}
}